name: dynamic_fonts
description: A package to include dynamic web-hosted fonts in your Flutter app.
version: 3.0.0
homepage: https://github.com/amake/dynamic-fonts-flutter/

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  path_provider: ^1.0.0
  crypto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  mustache: ^1.1.1
  pedantic: ^1.8.0
  protobuf: ^1.0.1
  console: ^3.1.0
